<?php
return [
    'locales' => [
        'fr-FR' => 'Francés (Francia)',
        'de-DE' => 'Alemán (Alemania)',
        'en-US' => 'Inglés (Estados Unidos)',
        'pt-BR' => 'Portugués (Brasil)',
        'en-GB' => 'Inglés (Reino Unido)',
        'es-ES' => 'Español (España)',
        'ar' => 'Árabe',
        'el' => 'Griego',
        'pt-AO' => 'Portugués (Angola)',
        'da' => 'Danés',
        'ja' => 'Japonés',
        'hu' => 'Húngaro',
        'vi' => 'Vietnamita',
        'en-CA' => 'Inglés (Canadá)',
        'es-MX' => 'Español (México)',
        'sv' => 'Sueco',
        'lt' => 'Lituano',
        'tr' => 'Turco',
        'fr-CA' => 'Francés (Canadá)',
        'fi' => 'Finlandés',
        'nl' => 'Neerlandés',
        'en-AU' => 'Inglés (Australia)',
        'pl' => 'Polaco',
        'fo' => 'Feroés',
        'lv' => 'Letón',
        'nb' => 'Noruego Bokmål',
        'ru' => 'Ruso',
        'es-PE' => 'Español (Perú)',
        'es-PR' => 'Español (Puerto Rico)',
        'it' => 'Italiano',
        'pt-PT' => 'Portugués (Portugal)',
        'ro' => 'Rumano',
        'is' => 'Islandés',
        'mk' => 'Macedonio',
        'sr' => 'Serbio',
        'sk' => 'Eslovaco',
        'si' => 'Esloveno',
        'es-DO' => 'Español (República Dominicana)',
        'bg' => 'Búlgaro',
        'en-IE' => 'Inglés (Irlanda)'
    ],
];